openapi: 3.0.0
info:
  description: Il seguente documento descrive le API messe a disposizione dall'Api Gateway della piattaforma Gamma
  version: "0.0.1"
  title: Api Gateway
paths:
  '/v1/emailsPreview/{tenantId}/{userId}':
    get:
      summary: Finds Emails preview by filtering criteria
      operationId: emailsPreviewByCriteria
      parameters:
        - name: tenantId
          in: path
          description: ID of user tenant
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
        - name: attachmentType
          in: query
          description: Type that need to be considered for filter
          required: false
          schema:
            type: array
            items:
              type: string
        - name: sender
          in: query
          description: Sender email that need to be considered for filter
          required: false
          schema:
            type: array
            items:
              type: string
        - name: from
          in: query
          description: Start date that need to be considered for filter
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: End date that need to be considered for filter
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/EmailResponseMessage'
  '/v1/signStoreAttachment/{tenantId}/{userId}/{attachmentId}':
    get:
      summary: Finds Emails preview by filtering criteria
      operationId: findPetsByStatus
      parameters:
        - name: tenantId
          in: path
          description: ID of user tenant
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
        - name: attachmentId
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/SignStoreResponseMessage'
components:
  schemas:
    Attachment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        name:
          type: string
    Result:
      type: object
      properties:
        resultCode:
          type: string
        description:
          type: string
    Email:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        sender:
          type: string
        recipient:
          type: string
        emailObject:
          type: string
        emailMessage:
          type: string
        sentOn:
          type: string
          format: date-time
        attachment:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    EmailResponseMessage:
      type: object
      properties:
        emails:
          type: array
          items:
            $ref: '#/components/schemas/Email'
        result:
          $ref: '#/components/schemas/Result'
    SignStoreResponseMessage:
      type: object
      properties:
        resultCode:
          type: string